import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className="min-h-screen bg-gradient-to-br from-slate-900 via-blue-900 to-slate-900">
				<header className="bg-black/20 backdrop-blur-sm border-b border-white/10">
					<div className="max-w-full mx-auto px-6 py-4">
						<div className="text-2xl font-bold text-white">
							&lt;DinoDev/&gt;
						</div>
					</div>
				</header>
				{children}
			</body>
		</html>
	);
}
